version: '3'
services:
    contacts:
        build:
            context: contacts
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        container_name: contacts
    video-rental:
        build: .
        ports:
            - "80:8080"
        container_name: video-rental