version: '3'
services:
    contacts:
        build:
            context: contacts
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        container_name: contacts
    video-rental:
        build: .
        ports:
            - "5000:80"
        container_name: video-rental